# Generated by Django 3.1.4 on 2020-12-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0003_auto_20201224_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='todayfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matno', models.TextField()),
                ('matdes', models.TextField()),
                ('date_of_forwarding', models.DateField()),
                ('plant', models.TextField()),
                ('batch', models.TextField()),
                ('platform', models.TextField()),
                ('cus_name', models.TextField()),
                ('kam_name', models.TextField()),
                ('qty', models.TextField()),
                ('value', models.TextField()),
                ('age', models.TextField()),
                ('log_qty_clear', models.TextField()),
                ('log_des_date', models.CharField(max_length=200)),
                ('kam_qty_clear', models.TextField()),
                ('kam_remarks', models.CharField(max_length=200)),
                ('kam_des_date', models.DateField()),
            ],
        ),
    ]
