# Generated by Django 3.1.4 on 2020-12-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0004_todayfg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todayfg',
            old_name='log_des_date',
            new_name='log_des_advice',
        ),
        migrations.RenameField(
            model_name='todayfg',
            old_name='log_qty_clear',
            new_name='log_remarks',
        ),
        migrations.RenameField(
            model_name='todayfg',
            old_name='value',
            new_name='value1',
        ),
        migrations.RemoveField(
            model_name='todayfg',
            name='date_of_forwarding',
        ),
    ]
