# Generated by Django 3.1.4 on 2020-12-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0005_auto_20201229_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayfg',
            name='kam_des_date',
            field=models.TextField(),
        ),
    ]
