# Generated by Django 3.1.4 on 2020-12-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0006_auto_20201229_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayfg',
            name='concat',
            field=models.TextField(default='None'),
        ),
    ]
