# Generated by Django 3.1.4 on 2020-12-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0007_todayfg_concat'),
    ]

    operations = [
        migrations.CreateModel(
            name='todayfg_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matno', models.TextField()),
                ('matdes', models.TextField()),
                ('plant', models.TextField()),
                ('batch', models.TextField()),
                ('platform', models.TextField()),
                ('cus_name', models.TextField()),
                ('kam_name', models.TextField()),
                ('qty', models.TextField()),
                ('value1', models.TextField()),
                ('concat', models.TextField(default='None')),
                ('age', models.TextField()),
                ('log_remarks', models.TextField()),
                ('log_des_advice', models.CharField(max_length=200)),
                ('kam_qty_clear', models.TextField()),
                ('kam_remarks', models.CharField(max_length=200)),
                ('kam_des_date', models.TextField()),
            ],
        ),
    ]
