# Generated by Django 3.1.4 on 2020-12-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgapp', '0009_todayfg_old_kam_des_advice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todayfg_old',
            old_name='kam_des_advice',
            new_name='kam_des_adv',
        ),
        migrations.AddField(
            model_name='todayfg',
            name='kam_des_adv',
            field=models.TextField(default='No'),
        ),
    ]
